version: '3.8'

services:
  db:
    image: postgres:15
    container_name: edunotas_db
    environment:
      POSTGRES_USER: edunotas
      POSTGRES_PASSWORD: securepassword
      POSTGRES_DB: edunotas_db
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - edunotas-net

  backend:
    build: ./backend
    container_name: edunotas_api
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://edunotas:securepassword@db:5432/edunotas_db
    expose:
      - "8000"
    networks:
      - edunotas-net

  frontend:
    build: ./frontend
    container_name: edunotas_frontend
    expose:
      - "80"
    networks:
      - edunotas-net

  nginx:
    image: nginx:latest
    container_name: edunotas_nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/certbot/conf:/etc/letsencrypt
      - ./nginx/certbot/www:/var/www/certbot
    depends_on:
      - frontend
      - backend
    networks:
      - edunotas-net

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./nginx/certbot/conf:/etc/letsencrypt
      - ./nginx/certbot/www:/var/www/certbot
    entrypoint: >
      sh -c 'certbot certonly --webroot --webroot-path=/var/www/certbot \
      --email tu-email@dominio.com --agree-tos --no-eff-email \
      -d dominio.com -d www.dominio.com'

networks:
  edunotas-net:
    driver: bridge

volumes:
  db_data:
